# Generated by Django 2.1.7 on 2019-03-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='css',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterModelTable(
            name='area',
            table='ihome_area',
        ),
        migrations.AlterModelTable(
            name='facility',
            table='ihome_facility',
        ),
        migrations.AlterModelTable(
            name='house',
            table='ihome_house',
        ),
        migrations.AlterModelTable(
            name='houseimage',
            table='ihome_house_image',
        ),
        migrations.AlterModelTable(
            name='order',
            table='ihome_order',
        ),
        migrations.AlterModelTable(
            name='user',
            table='ihome_user',
        ),
    ]
